apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: utvikling-admin
  namespace: utvikling-admin
  name: brillestotte-for-katter

spec:
  ingresses:
    - https://brillestøtte-for-katter.nav.no/
  image: {{image}}
  port: 3000